#!/bin/bash

runtag=$1
failfile="$runtag.failed"

# command line python call to submit jobs
python FoundationJobSubmit.py --username=dchouras --password=XXXXXX --inputFile=input --paramFile=param --outputFile=output --app=head-stampede-5.97u2 --runTag=run1 --archive=true --dependency=true

# command line python call to get status of all the jobs for pipeline instance
python PipelinesUtil.py --username=dchouras --password=XXXXXX --status=true --runTag=run1

# command line python call to poll over job specified in dependency file
python PipelinesUtil.py --username=dchouras --password=XXXXXX --poll=true --runTag=run1 



if [ -f "$failfile" ]
then
	echo "Pipeline $runtag failed."
	exit
fi

# here we can submit the next job, as there is no failed file which implies dependency is fullfilled.



